version: "3.9"
services:
    database:
        image: mysql:8.0
        container_name: database
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        volumes:
            -   data:/var/lib/mysql
        networks:
            - laravel
    app:
       build:
           args:
               user: root
           context: .
           target: php-fpm
           dockerfile: Dockerfile
       image: app
       environment:
           - APP_ENV=${APP_ENV}
           - DB_HOST=database
       container_name: laravel-app
       restart: unless-stopped
       working_dir: /var/www
       volumes:
           -   ./:/var/www
       depends_on:
           -   database
       networks:
           - laravel
    nginx:
        image: nginx
        container_name: web-server
        restart: unless-stopped
        ports:
            -   "8001:80"
        volumes:
            -   ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel
        working_dir: /var/www
networks:
    laravel:
        driver: bridge
volumes:
    data: ~
